[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "yahooweather-cli"
version = "0.0.10"
authors = [{ name = "tomok14", email = "nolamiller1203@gmail.com" }]
description = "yahooweather command line tool"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "rich",
    "beautifulsoup4",
    "tomlkit",
    "requests-cache",
    "wcwidth",
]

[project.urls]
Homepage = "https://github.com/tomok14/yahooweather"
Issues = "https://github.com/tomok14/yahooweather/issues"

[tool.setuptools.packages.find]
where = ["src"]


[tool.setuptools.package-data]
yahooweather = ["data/location.db"]

[project.scripts]
yahooweather = "yahooweather.yahooweather:main"

[tool.pylint.main]
source-roots = ["src"]
